# Generated by Django 5.2.12 on 2026-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
