# Generated by Django 5.2.12 on 2026-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_companyprofile_address_companyprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
