# Generated by Django 5.2.12 on 2026-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
