# Generated by Django 5.2.12 on 2026-03-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("skills_required", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("pfe", "PFE"),
                            ("observation", "Observation"),
                            ("internship", "Internship"),
                        ],
                        default="internship",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("application_deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
